### ISSUE TITLE
Error when parsing large files

### ISSUE THREAD

**Issue by andrewhack** [josevnz/SuricataLog#7]
(Reported as: Not working - error: self = <textual._animator.Animator object at 0x7f88f0a57f90>)

Error when executing eve_log.py

```
. ~/virtualenv/suricatalog/bin/activate; pip3 install --upgrade SuricataLog
Python 3.11.2
Linux host 6.1.0-11-amd64 https://github.com/josevnz/SuricataLog/pull/1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux
eve_log.py --timestamp '2015-01-01 10:41:21.642899' --formats table /var/log/suricata/eve.json

. ~/virtualenv/suricatalog/bin/activate && pip freeze
commonmark==0.9.1
Pygments==2.16.1
rich==12.4.4
SuricataLog==0.0.8
textual==0.1.18
```

![image](https://github.com/josevnz/SuricataLog/assets/46722365/da787876-5dc8-4556-a2bf-5b3c05811d6e)

**Comment by josevnz** [comment]
Thanks, I'll take a look. I did suspect what it is, let me try to reproduce.

**Comment by josevnz** [comment]
Looks like it is a race condition of some sorts on Textual. I managed to reproduce an error on the following with a much larger eve.json file (17M):


|OS|Python|Error|
|----|----------|--------|
|Fedora release 37|3.11.4|No rendering|
|Ubuntu Armbian 23.02.2 Jammy|3.10|Textual exception|
|Ubuntu 20.04.4 LTS (Focal Fossa)|3.8.10|Textual exception|


Out of curiosity, what is the size of your eve.json file?
Would be possible for you to share it ro reproduce the same error? (not sure if you have to scrub the data first)

**Comment by josevnz** [comment]
Thanks, this will be very useful!
